ci(Ubuntu version): Upgrade to 20.04
Attempt to avoid folloing error by upgrading SQLite:

```
django.db.utils.NotSupportedError: Renaming the 'djstripe_paymentmethod' table while in a transaction is not supported on SQLite < 3.26 because it would break referential integrity. Try adding `atomic = False` to the Migration class.
```

See https://github.com/dj-stripe/dj-stripe/issues/1289